name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Deno
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x # Usar la versión de Deno requerida por tu proyecto

    - name: Cache Deno Dependencies
      run: deno cache deps.ts # Cambia deps.ts por el archivo donde declares tus dependencias

    - name: Build
      run: deno task build # Cambia "build" por la tarea que uses en tu archivo deno.json o deno.jsonc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

